# Generated by Django 3.1.7 on 2021-11-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20211130_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, default='In Stock', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='status_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
