# Generated by Django 3.1.7 on 2021-11-30 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0003_auto_20211130_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='admin_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='admin_status',
            field=models.CharField(blank=True, default='Pending', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='pending', max_length=100, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_receiver_product', to='user_app.product')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_receiver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Trade',
            },
        ),
    ]
